/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package FORMULAIRES;

import ENTITES.Directions;
import ENTITES.Divisions;
import ENTITES.Grades;
import javax.swing.JOptionPane;

/**
 *
 * @author LE GRAND AL
 */
public class JpConfigPresence extends javax.swing.JPanel {

    /**
     * Creates new form JpConfigPresence
     */
    public JpConfigPresence() {
        initComponents();
    }
    Directions dir = new Directions();
    Divisions div = new Divisions();
    Grades gd = new Grades();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PM = new javax.swing.JPopupMenu();
        miActualiser = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        miAjouter = new javax.swing.JMenuItem();
        miModifier = new javax.swing.JMenuItem();
        miSupprimer = new javax.swing.JMenuItem();
        PMDiv = new javax.swing.JPopupMenu();
        miActualiser1 = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        miAjouterDiv = new javax.swing.JMenuItem();
        miModifierDiv = new javax.swing.JMenuItem();
        miSupprimerDiv = new javax.swing.JMenuItem();
        PMGrade = new javax.swing.JPopupMenu();
        miActualiserGd = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        miAjouterGd = new javax.swing.JMenuItem();
        miModifierGd = new javax.swing.JMenuItem();
        miSupprimerGd = new javax.swing.JMenuItem();
        JTP = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        txtRechGd = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        JtGrade = new javax.swing.JTable();
        btnNouveauGrade = new javax.swing.JButton();
        btnActuaGrade = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtRechDiv = new javax.swing.JTextField();
        btnNouveauDiv = new javax.swing.JButton();
        btnActuaDiv = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        JtDivision = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JtDirection = new javax.swing.JTable();
        txtRech = new javax.swing.JTextField();
        btnNouveauDirect = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnActuaDirect = new javax.swing.JButton();

        miActualiser.setText("Actualiser");
        miActualiser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miActualiserActionPerformed(evt);
            }
        });
        PM.add(miActualiser);
        PM.add(jSeparator1);

        miAjouter.setText("Ajouter");
        miAjouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miAjouterActionPerformed(evt);
            }
        });
        PM.add(miAjouter);

        miModifier.setText("Modifier");
        miModifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miModifierActionPerformed(evt);
            }
        });
        PM.add(miModifier);

        miSupprimer.setText("Supprimer");
        miSupprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miSupprimerActionPerformed(evt);
            }
        });
        PM.add(miSupprimer);

        miActualiser1.setText("Actualiser");
        miActualiser1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miActualiser1ActionPerformed(evt);
            }
        });
        PMDiv.add(miActualiser1);
        PMDiv.add(jSeparator2);

        miAjouterDiv.setText("Ajouter");
        miAjouterDiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miAjouterDivActionPerformed(evt);
            }
        });
        PMDiv.add(miAjouterDiv);

        miModifierDiv.setText("Modifier");
        miModifierDiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miModifierDivActionPerformed(evt);
            }
        });
        PMDiv.add(miModifierDiv);

        miSupprimerDiv.setText("Supprimer");
        miSupprimerDiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miSupprimerDivActionPerformed(evt);
            }
        });
        PMDiv.add(miSupprimerDiv);

        miActualiserGd.setText("Actualiser");
        miActualiserGd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miActualiserGdActionPerformed(evt);
            }
        });
        PMGrade.add(miActualiserGd);
        PMGrade.add(jSeparator3);

        miAjouterGd.setText("Ajouter");
        miAjouterGd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miAjouterGdActionPerformed(evt);
            }
        });
        PMGrade.add(miAjouterGd);

        miModifierGd.setText("Modifier");
        miModifierGd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miModifierGdActionPerformed(evt);
            }
        });
        PMGrade.add(miModifierGd);

        miSupprimerGd.setText("Supprimer");
        miSupprimerGd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miSupprimerGdActionPerformed(evt);
            }
        });
        PMGrade.add(miSupprimerGd);

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 51), 3));

        JTP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JTPMouseClicked(evt);
            }
        });

        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 255, 0), 1, true));

        txtRechGd.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtRechGd.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtRechGdCaretUpdate(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Recherche");

        JtGrade.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        JtGrade.setComponentPopupMenu(PMGrade);
        JtGrade.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JtGradeMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(JtGrade);

        btnNouveauGrade.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnNouveauGrade.setText("Nouveau");
        btnNouveauGrade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNouveauGradeActionPerformed(evt);
            }
        });

        btnActuaGrade.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnActuaGrade.setText("Actualiser");
        btnActuaGrade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActuaGradeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtRechGd, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(128, 128, 128)
                        .addComponent(btnNouveauGrade, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                        .addComponent(btnActuaGrade, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtRechGd, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE))
                    .addComponent(btnActuaGrade, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnNouveauGrade, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)
                .addGap(12, 12, 12))
        );

        JTP.addTab("Grade", jPanel1);

        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 51), 1, true));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Recherche");

        txtRechDiv.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtRechDiv.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtRechDivCaretUpdate(evt);
            }
        });

        btnNouveauDiv.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnNouveauDiv.setText("Nouveau");
        btnNouveauDiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNouveauDivActionPerformed(evt);
            }
        });

        btnActuaDiv.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnActuaDiv.setText("Actualiser");
        btnActuaDiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActuaDivActionPerformed(evt);
            }
        });

        JtDivision.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        JtDivision.setComponentPopupMenu(PMDiv);
        JtDivision.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JtDivisionMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(JtDivision);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtRechDiv, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(128, 128, 128)
                        .addComponent(btnNouveauDiv, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                        .addComponent(btnActuaDiv, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtRechDiv, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE))
                    .addComponent(btnActuaDiv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnNouveauDiv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)
                .addGap(12, 12, 12))
        );

        JTP.addTab("Division", jPanel2);

        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        JtDirection.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        JtDirection.setComponentPopupMenu(PM);
        JtDirection.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JtDirectionMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(JtDirection);

        txtRech.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtRech.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtRechCaretUpdate(evt);
            }
        });

        btnNouveauDirect.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnNouveauDirect.setText("Nouveau");
        btnNouveauDirect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNouveauDirectActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Recherche");

        btnActuaDirect.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnActuaDirect.setText("Actualiser");
        btnActuaDirect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActuaDirectActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtRech, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(128, 128, 128)
                        .addComponent(btnNouveauDirect, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                        .addComponent(btnActuaDirect, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtRech, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE))
                    .addComponent(btnActuaDirect, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnNouveauDirect, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 336, Short.MAX_VALUE)
                .addGap(12, 12, 12))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        JTP.addTab("Direction", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JTP)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JTP)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void JTPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JTPMouseClicked
        // TODO add your handling code here:
        int n = JTP.getSelectedIndex();
        System.out.println(n);
        if (n == 2) {
            dir.remplir(JtDirection, "select * from t_direction order by libdirect");
        } else if (n == 1) {
        } else if (n == 0) {
        }

    }//GEN-LAST:event_JTPMouseClicked

    private void btnNouveauDirectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNouveauDirectActionPerformed
        // TODO add your handling code here:
        JdDirection jd = new JdDirection(null, true);
        jd.type = "ajouter";
        jd.setVisible(true);
        dir.remplir(JtDirection, "select * from t_direction order by libdirect");
    }//GEN-LAST:event_btnNouveauDirectActionPerformed
    String iddir, libdir;
    private void JtDirectionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JtDirectionMouseClicked
        // TODO add your handling code here:
        iddir = JtDirection.getValueAt(JtDirection.getSelectedRow(), 0).toString();
        libdir = JtDirection.getValueAt(JtDirection.getSelectedRow(), 1).toString();

    }//GEN-LAST:event_JtDirectionMouseClicked

    private void miActualiserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miActualiserActionPerformed
        // TODO add your handling code here:
        dir.remplir(JtDirection, "select * from t_direction order by libdirect");
        txtRech.setText("");
        txtRech.requestFocus();
    }//GEN-LAST:event_miActualiserActionPerformed

    private void miAjouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miAjouterActionPerformed
        // TODO add your handling code here:
        btnNouveauDirectActionPerformed(evt);
    }//GEN-LAST:event_miAjouterActionPerformed

    private void miModifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miModifierActionPerformed
        // TODO add your handling code here:
        int test = JOptionPane.showConfirmDialog(null, "Voulez-vous modifier cette informations ?", "Modification", JOptionPane.YES_NO_OPTION);
        if (test == JOptionPane.YES_OPTION) {
            JdDirection jd = new JdDirection(null, true);
            jd.type = "modifier";
            jd.txtID.setText(iddir);
            jd.txtNom.setText(libdir);
            jd.setVisible(true);
            dir.remplir(JtDirection, "select * from t_direction order by libdirect");
        }
    }//GEN-LAST:event_miModifierActionPerformed

    private void miSupprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miSupprimerActionPerformed
        // TODO add your handling code here:
        int test = JOptionPane.showConfirmDialog(null, "Voulez-vous modifier cette informations ?", "Modification", JOptionPane.YES_NO_OPTION);
        if (test == JOptionPane.YES_OPTION) {
            dir.setIddirectn(iddir);
            dir.Supprimer();
            dir.remplir(JtDirection, "select * from t_direction order by libdirect");
        }
    }//GEN-LAST:event_miSupprimerActionPerformed

    private void txtRechCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtRechCaretUpdate
        // TODO add your handling code here:
        dir.remplir(JtDirection, "select * from t_direction where iddirect like '" + txtRech.getText() + "%' or libdirect like '" + txtRech.getText() + "%' order by libdirect");
    }//GEN-LAST:event_txtRechCaretUpdate

    private void btnActuaDirectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActuaDirectActionPerformed
        // TODO add your handling code here:
        dir.remplir(JtDirection, "select * from t_direction order by libdirect");
    }//GEN-LAST:event_btnActuaDirectActionPerformed

    private void txtRechDivCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtRechDivCaretUpdate
        // TODO add your handling code here:
        div.remplir(JtDivision, "SELECT t_division.iddiv,t_division.libdiv,t_direction.libdirect "
                + "FROM t_division,t_direction "
                + "WHERE t_division.iddirect = t_direction.iddirect and (t_division.libdiv like '" + txtRechDiv.getText() + "%' or "
                + "t_direction.libdirect like '" + txtRechDiv.getText() + "%' or t_division.iddiv like '" + txtRechDiv.getText() + "%' )");
    }//GEN-LAST:event_txtRechDivCaretUpdate

    private void btnNouveauDivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNouveauDivActionPerformed
        // TODO add your handling code here:
        JdDivision jd = new JdDivision(null, true);
        jd.type = "ajouter";
        jd.setVisible(true);
        div.remplir(JtDivision, "SELECT t_division.iddiv,t_division.libdiv,t_direction.libdirect FROM t_division,t_direction WHERE t_division.iddirect = t_direction.iddirect");
    }//GEN-LAST:event_btnNouveauDivActionPerformed

    private void btnActuaDivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActuaDivActionPerformed
        // TODO add your handling code here:
        div.remplir(JtDivision, "SELECT t_division.iddiv,t_division.libdiv,t_direction.libdirect FROM t_division,t_direction WHERE t_division.iddirect = t_direction.iddirect");
    }//GEN-LAST:event_btnActuaDivActionPerformed
    String id_div, lib_div, lib_dir;
    private void JtDivisionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JtDivisionMouseClicked
        // TODO add your handling code here:
        id_div = JtDivision.getValueAt(JtDivision.getSelectedRow(), 0).toString();
        lib_div = JtDivision.getValueAt(JtDivision.getSelectedRow(), 1).toString();
        lib_dir = JtDivision.getValueAt(JtDivision.getSelectedRow(), 2).toString();
    }//GEN-LAST:event_JtDivisionMouseClicked

    private void miActualiser1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miActualiser1ActionPerformed
        // TODO add your handling code here:
        btnActuaDivActionPerformed(evt);
    }//GEN-LAST:event_miActualiser1ActionPerformed

    private void miAjouterDivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miAjouterDivActionPerformed
        // TODO add your handling code here:
        btnNouveauDivActionPerformed(evt);
    }//GEN-LAST:event_miAjouterDivActionPerformed

    private void miModifierDivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miModifierDivActionPerformed
        // TODO add your handling code here:
        JdDivision jd = new JdDivision(null, true);
        jd.type = "modifier";
        jd.txtID.setText(id_div);
        jd.txtNom.setText(lib_div);
        jd.cbo.setSelectedItem(lib_dir);
        jd.setVisible(true);
        div.remplir(JtDivision, "SELECT t_division.iddiv,t_division.libdiv,t_direction.libdirect FROM t_division,t_direction WHERE t_division.iddirect = t_direction.iddirect");

    }//GEN-LAST:event_miModifierDivActionPerformed

    private void miSupprimerDivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miSupprimerDivActionPerformed
        // TODO add your handling code here:
        int test = JOptionPane.showConfirmDialog(null, "Voulez-vous modifier cette informations ?", "Modification", JOptionPane.YES_NO_OPTION);
        if (test == JOptionPane.YES_OPTION) {
            div.setIddv(id_div);
            div.Supprimer();
            div.remplir(JtDivision, "SELECT t_division.iddiv,t_division.libdiv,t_direction.libdirect FROM t_division,t_direction WHERE t_division.iddirect = t_direction.iddirect");
        }
    }//GEN-LAST:event_miSupprimerDivActionPerformed

    private void txtRechGdCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtRechGdCaretUpdate
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRechGdCaretUpdate
    String id_gd, lib_gd;
    private void JtGradeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JtGradeMouseClicked
        // TODO add your handling code here:
        id_gd = JtGrade.getValueAt(JtGrade.getSelectedRow(), 0).toString();
        lib_gd = JtGrade.getValueAt(JtGrade.getSelectedRow(), 1).toString();
    }//GEN-LAST:event_JtGradeMouseClicked

    private void btnNouveauGradeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNouveauGradeActionPerformed
        // TODO add your handling code here:
        JdGrade jg = new JdGrade(null, true);
        jg.type = "ajouter";
        jg.setVisible(true);
        gd.remplir(JtGrade, "select * from t_grade order by libgrade");
    }//GEN-LAST:event_btnNouveauGradeActionPerformed

    private void btnActuaGradeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActuaGradeActionPerformed
        // TODO add your handling code here:
        gd.remplir(JtGrade, "select * from t_grade order by libgrade");
        txtRechGd.setText("");
    }//GEN-LAST:event_btnActuaGradeActionPerformed

    private void miActualiserGdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miActualiserGdActionPerformed
        // TODO add your handling code here:
        btnActuaGradeActionPerformed(evt);
    }//GEN-LAST:event_miActualiserGdActionPerformed

    private void miAjouterGdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miAjouterGdActionPerformed
        // TODO add your handling code here:
        btnNouveauGradeActionPerformed(evt);
    }//GEN-LAST:event_miAjouterGdActionPerformed

    private void miModifierGdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miModifierGdActionPerformed
        // TODO add your handling code here:
        JdGrade jg = new JdGrade(null, true);
        jg.type = "modifier";
        jg.txtID.setText(id_gd);
        jg.txtNom.setText(lib_gd);
        jg.setVisible(true);
        gd.remplir(JtGrade, "select * from t_grade order by libgrade");
    }//GEN-LAST:event_miModifierGdActionPerformed

    private void miSupprimerGdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miSupprimerGdActionPerformed
        // TODO add your handling code here:
        int test = JOptionPane.showConfirmDialog(null, "Voulez-vous modifier cette informations ?", "Modification", JOptionPane.YES_NO_OPTION);
        if (test == JOptionPane.YES_OPTION) {
            gd.setIdgrde(id_gd);
            gd.Supprimer();
            gd.remplir(JtGrade, "select * from t_grade order by libgrade");
        }
    }//GEN-LAST:event_miSupprimerGdActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane JTP;
    private javax.swing.JTable JtDirection;
    private javax.swing.JTable JtDivision;
    private javax.swing.JTable JtGrade;
    private javax.swing.JPopupMenu PM;
    private javax.swing.JPopupMenu PMDiv;
    private javax.swing.JPopupMenu PMGrade;
    private javax.swing.JButton btnActuaDirect;
    private javax.swing.JButton btnActuaDiv;
    private javax.swing.JButton btnActuaGrade;
    private javax.swing.JButton btnNouveauDirect;
    private javax.swing.JButton btnNouveauDiv;
    private javax.swing.JButton btnNouveauGrade;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JMenuItem miActualiser;
    private javax.swing.JMenuItem miActualiser1;
    private javax.swing.JMenuItem miActualiserGd;
    private javax.swing.JMenuItem miAjouter;
    private javax.swing.JMenuItem miAjouterDiv;
    private javax.swing.JMenuItem miAjouterGd;
    private javax.swing.JMenuItem miModifier;
    private javax.swing.JMenuItem miModifierDiv;
    private javax.swing.JMenuItem miModifierGd;
    private javax.swing.JMenuItem miSupprimer;
    private javax.swing.JMenuItem miSupprimerDiv;
    private javax.swing.JMenuItem miSupprimerGd;
    private javax.swing.JTextField txtRech;
    private javax.swing.JTextField txtRechDiv;
    private javax.swing.JTextField txtRechGd;
    // End of variables declaration//GEN-END:variables
}
