/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FORMULAIRES;

import ENTITES.Agent;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.Timer;

/**
 *
 * @author MECHACK
 */
public class JpRapport extends javax.swing.JPanel {

    /**
     * Creates new form Agents
     */
    public JpRapport() {
        initComponents();
        pres.remplir(JtPresence);
    }
    Timer t;
    int x = 10;

 
    ENTITES.Presences pres = new ENTITES.Presences();

    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pm = new javax.swing.JPopupMenu();
        miActualiser = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        miAjouter = new javax.swing.JMenuItem();
        miModifier = new javax.swing.JMenuItem();
        jScrollPane1 = new javax.swing.JScrollPane();
        JtPresence = new javax.swing.JTable();

        miActualiser.setText("Actualiser");
        miActualiser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miActualiserActionPerformed(evt);
            }
        });
        pm.add(miActualiser);
        pm.add(jSeparator1);

        miAjouter.setText("Ajouter");
        miAjouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miAjouterActionPerformed(evt);
            }
        });
        pm.add(miAjouter);

        miModifier.setText("Modifier");
        miModifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miModifierActionPerformed(evt);
            }
        });
        pm.add(miModifier);

        JtPresence.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(JtPresence);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 850, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 446, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void miAjouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miAjouterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_miAjouterActionPerformed
    private void miModifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miModifierActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_miModifierActionPerformed

    private void miActualiserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miActualiserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_miActualiserActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable JtPresence;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenuItem miActualiser;
    private javax.swing.JMenuItem miAjouter;
    private javax.swing.JMenuItem miModifier;
    private javax.swing.JPopupMenu pm;
    // End of variables declaration//GEN-END:variables
}
